/* Catálogo Dibaq Perú: Natural Moments y Sense, perros y gatos.
   Este archivo alimenta el buscador, los conteos de cada sección y las fichas de producto.
   Para agregar, quitar o corregir un producto basta con editar este arreglo.

   Campos
   - id:          nombre del archivo de la foto en img/productos/<id>.webp
   - linea:       "nm" (Natural Moments) o "sense"
   - especie:     "perro" o "gato"
   - edad:        "cachorro" (también gatito), "adulto", "senior"
   - tamano:      solo perros: "mini" (hasta 10 kg), "mediano" (11 a 25 kg), "grande" (más de 25 kg)
   - proteinas:   proteínas animales principales, en el orden del empaque
   - contiene:    lo que excluyen los filtros "Sin…": salmon, pescado (cualquier pescado, krill o aceite de pescado),
                  pavo, pollo, cordero, pato, cereales
   - necesidades: alergias, digestion, peso, articulaciones, urinario, esterilizado, pelaje
   - analisis:    porcentajes del análisis garantizado; kcal = energía metabolizable por kg (null si no se tiene)
   - verificar:   true mientras los datos vengan de fichas de tiendas y no del empaque */
window.DIBAQ_CATALOGO = [
  /* ================= DIBAQ SENSE · PERROS ================= */
  {
    id: "sense-perro-cachorro-salmon-pavo",
    linea: "sense", especie: "perro", edad: ["cachorro"], tamano: ["mini", "mediano", "grande"],
    nombre: "Cachorro salmón y pavo",
    completo: "Dibaq Sense Grain Free Puppy Salmón y Pavo",
    resumen: "Hipoalergénico y sin cereales para cachorros de todas las razas.",
    descripcion: "Su primera receta sin cereales: carne fresca de pavo y salmón fresco para un crecimiento con digestión tranquila. Sin trigo, maíz, soja, gluten ni huevo.",
    proteinas: ["Pavo", "Salmón"],
    contiene: ["salmon", "pescado", "pavo"],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Pavo fresco", "20 %"], ["Salmón fresco", "20 %"]],
    sinIngredientes: ["Trigo", "Maíz", "Soja", "Gluten", "Huevo"],
    analisis: null,
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "sense-perro-salmon",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Salmón",
    completo: "Dibaq Sense Grain Free Salmón Adulto",
    resumen: "Salmón fresco como primer ingrediente para piel y pelo sensibles.",
    descripcion: "Una sola fuente de proteína animal, el salmón, para perros adultos con alergias o piel reactiva. Sus omega 3 ayudan a mantener la piel y el pelo.",
    proteinas: ["Salmón"],
    contiene: ["salmon", "pescado"],
    necesidades: ["alergias", "digestion", "pelaje"],
    ingredientes: [["Salmón fresco", "1.er ingrediente"]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: 26, grasa: 15, fibra: 2.8, ceniza: 5.9, kcal: null },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "sense-perro-salmon-mini",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini"],
    nombre: "Salmón mini",
    completo: "Dibaq Sense Grain Free Salmón Mini",
    resumen: "Más de 70 % de pescado, en croqueta para razas pequeñas.",
    descripcion: "Salmón y arenque frescos en una receta pensada para bocas pequeñas y estómagos delicados. Rica en omega 3 para un pelaje brillante.",
    proteinas: ["Salmón", "Arenque"],
    contiene: ["salmon", "pescado"],
    necesidades: ["alergias", "digestion", "pelaje"],
    ingredientes: [["Salmón fresco", "25 %"], ["Salmón deshidratado", "23 %"], ["Arenque fresco", "22 %"]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: 26, grasa: null, fibra: null, ceniza: null, kcal: 3648 },
    formatos: ["500 g", "2 kg", "6 kg"],
    verificar: true
  },
  {
    id: "sense-perro-cordero",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Cordero",
    completo: "Dibaq Sense Grain Free Cordero Adulto",
    resumen: "Monoproteico de cordero para perros con intolerancias.",
    descripcion: "El cordero como única proteína animal, para perros que no toleran el pollo ni otras carnes. Lleva aceite de salmón como fuente de omega 3.",
    proteinas: ["Cordero"],
    contiene: ["cordero", "pescado"],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Cordero fresco", "33 %"], ["Cordero deshidratado", "25 %"], ["Aceite de salmón", ""]],
    sinIngredientes: ["Cereales", "Gluten", "Pollo"],
    analisis: { proteina: 28, grasa: 17, fibra: 2.2, ceniza: null, kcal: null },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "sense-perro-cordero-mini",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini"],
    nombre: "Cordero mini",
    completo: "Dibaq Sense Grain Free Cordero Mini",
    resumen: "Cordero fresco y judías verdes para razas pequeñas.",
    descripcion: "La receta monoproteica de cordero en croqueta pequeña. Hipoalergénica y sin cereales, para perros pequeños con digestión sensible.",
    proteinas: ["Cordero"],
    contiene: ["cordero"],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Cordero fresco", "1.er ingrediente"], ["Judías verdes", ""]],
    sinIngredientes: ["Cereales", "Gluten", "Pollo"],
    analisis: null,
    formatos: ["2 kg", "6 kg"],
    verificar: true
  },
  {
    id: "sense-perro-pollo-pato",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Pollo y pato",
    completo: "Dibaq Sense Grain Free Pollo y Pato",
    resumen: "Carnes frescas de pollo y pato, sin cereales.",
    descripcion: "Dos carnes frescas y magras para perros adultos activos que necesitan una receta sin cereales y fácil de digerir.",
    proteinas: ["Pollo", "Pato"],
    contiene: ["pollo", "pato"],
    necesidades: ["digestion"],
    ingredientes: [["Pollo fresco", ""], ["Pato fresco", ""]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: 26, grasa: 15, fibra: null, ceniza: null, kcal: null },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "sense-perro-conejo",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Conejo",
    completo: "Dibaq Sense Grain Free Sensitive Digestion Conejo",
    resumen: "Conejo fresco para digestiones delicadas.",
    descripcion: "Una carne poco habitual y muy digestible, pensada para perros con estómago sensible o que ya probaron otras proteínas.",
    proteinas: ["Conejo", "Pavo"],
    contiene: ["pavo"],
    necesidades: ["digestion", "alergias"],
    ingredientes: [["Conejo fresco", "35 %"], ["Pavo deshidratado", "25 %"]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: 26, grasa: 15, fibra: 2.8, ceniza: null, kcal: null },
    formatos: null,
    verificar: true
  },
  {
    id: "sense-perro-wild",
    linea: "sense", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Wild ciervo y jabalí",
    completo: "Dibaq Sense Grain Free Wild",
    resumen: "Ciervo y jabalí para perros intolerantes al pollo.",
    descripcion: "Proteínas de caza, sin pollo y sin gluten, para perros que necesitan salir de las carnes de siempre.",
    proteinas: ["Ciervo", "Jabalí"],
    contiene: [],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Ciervo", ""], ["Jabalí", ""]],
    sinIngredientes: ["Cereales", "Gluten", "Pollo"],
    analisis: { proteina: 26, grasa: 15, fibra: 2.8, ceniza: null, kcal: null },
    formatos: null,
    verificar: true
  },
  {
    id: "sense-perro-light-senior",
    linea: "sense", especie: "perro", edad: ["adulto", "senior"], tamano: ["mini", "mediano", "grande"],
    nombre: "Light y senior pato y pavo",
    completo: "Dibaq Sense Grain Free Light & Senior Pato y Pavo",
    resumen: "Para mayores de 7 años o con tendencia a subir de peso.",
    descripcion: "Menos grasa, L-carnitina y protectores articulares (glucosamina, condroitina y MSM) para acompañar la madurez sin sumar kilos.",
    proteinas: ["Pato", "Pollo", "Pavo"],
    contiene: ["pato", "pollo", "pavo"],
    necesidades: ["peso", "articulaciones", "digestion"],
    ingredientes: [["Pato fresco", "20 %"], ["Pollo fresco", "20 %"], ["Pavo deshidratado", "18 %"]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: null, grasa: 9, fibra: null, ceniza: null, kcal: null },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },

  /* ================= DIBAQ SENSE · GATOS ================= */
  {
    id: "sense-gato-kitten",
    linea: "sense", especie: "gato", edad: ["cachorro"], tamano: [],
    nombre: "Gatito pavo y salmón",
    completo: "Dibaq Sense Grain Free Kitten Pavo y Salmón",
    resumen: "Hipoalergénico, del primer mes a los 12 meses.",
    descripcion: "Pavo y salmón frescos, sin cereales, para gatitos de todas las razas durante todo su primer año.",
    proteinas: ["Pavo", "Salmón"],
    contiene: ["pavo", "salmon", "pescado"],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Pavo fresco", ""], ["Salmón fresco", ""]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: null,
    formatos: ["1.5 kg", "6 kg"],
    verificar: true
  },
  {
    id: "sense-gato-esterilizado",
    linea: "sense", especie: "gato", edad: ["adulto"], tamano: [],
    nombre: "Esterilizado pollo y pato",
    completo: "Dibaq Sense Grain Free Sterilized Pollo y Pato",
    resumen: "Para gatos esterilizados con tendencia a engordar.",
    descripcion: "Pollo y pato frescos con champiñones, arándanos, mango y manzana. Extracto de malta contra las bolas de pelo, L-carnitina, taurina y complejos renal, dental y articular.",
    proteinas: ["Pollo", "Pato"],
    contiene: ["pollo", "pato"],
    necesidades: ["esterilizado", "peso", "articulaciones"],
    ingredientes: [["Pollo fresco", ""], ["Pato fresco", ""], ["Arándanos, mango y manzana", ""]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: null,
    formatos: ["1.5 kg", "6 kg"],
    verificar: true
  },
  {
    id: "sense-gato-urinary",
    linea: "sense", especie: "gato", edad: ["adulto"], tamano: [],
    nombre: "Urinary salmón y atún",
    completo: "Dibaq Sense Grain Free Urinary Salmón y Atún",
    resumen: "Cuida las vías urinarias de gatos adultos y esterilizados.",
    descripcion: "Salmón y atún frescos con zanahoria, espinaca, arándano y manzana. Hipoalergénico y sin cereales.",
    proteinas: ["Salmón", "Atún"],
    contiene: ["salmon", "pescado"],
    necesidades: ["urinario", "esterilizado", "alergias"],
    ingredientes: [["Salmón fresco", ""], ["Atún fresco", ""], ["Arándano", ""]],
    sinIngredientes: ["Cereales", "Gluten"],
    analisis: { proteina: 34, grasa: 13, fibra: null, ceniza: null, kcal: null },
    formatos: ["1.5 kg", "6 kg"],
    verificar: true
  },

  /* ================= NATURAL MOMENTS · PERROS (5 Star) ================= */
  {
    id: "nm-perro-cachorro-mediano",
    linea: "nm", especie: "perro", edad: ["cachorro"], tamano: ["mediano"],
    nombre: "Cachorro razas medianas",
    completo: "Dibaq Natural Moments 5 Star Pavo y Pollo Cachorro Razas Medianas",
    resumen: "Pavo y pollo con arroz como único cereal.",
    descripcion: "Para cachorros de razas medianas en pleno crecimiento: proteína de pavo y pollo, arroz como único cereal y hierbas mediterráneas.",
    proteinas: ["Pavo", "Pollo"],
    contiene: ["pavo", "pollo", "cereales"],
    necesidades: [],
    ingredientes: [["Pavo", "23 %"], ["Pollo deshidratado", "20 %"], ["Arroz", "18 %"]],
    sinIngredientes: ["Trigo", "Maíz"],
    analisis: null,
    formatos: ["12 kg"],
    verificar: true
  },
  {
    id: "nm-perro-cachorro-grande",
    linea: "nm", especie: "perro", edad: ["cachorro"], tamano: ["grande"],
    nombre: "Cachorro razas grandes",
    completo: "Dibaq Natural Moments 5 Star Pavo y Pollo Cachorro Razas Grandes",
    resumen: "41 % de pavo y pollo para crecer con huesos fuertes.",
    descripcion: "Energía medida para el crecimiento lento de las razas grandes, con pavo y pollo y arroz como único cereal.",
    proteinas: ["Pavo", "Pollo"],
    contiene: ["pavo", "pollo", "cereales"],
    necesidades: ["articulaciones"],
    ingredientes: [["Pavo y pollo", "41 %"], ["Arroz", "único cereal"]],
    sinIngredientes: ["Trigo", "Maíz"],
    analisis: { proteina: null, grasa: null, fibra: null, ceniza: null, kcal: 3650 },
    formatos: null,
    verificar: true
  },
  {
    id: "nm-perro-adulto-mini",
    linea: "nm", especie: "perro", edad: ["adulto"], tamano: ["mini"],
    nombre: "Adulto razas pequeñas",
    completo: "Dibaq Natural Moments Pavo y Pollo Adulto Razas Pequeñas",
    resumen: "Croqueta pequeña con pavo, pollo y arroz.",
    descripcion: "Para perros pequeños con mucha energía: pavo y pollo, arroz como único cereal y sin gluten.",
    proteinas: ["Pavo", "Pollo"],
    contiene: ["pavo", "pollo", "cereales"],
    necesidades: [],
    ingredientes: [["Pavo", "21 %"], ["Pollo deshidratado", "20 %"], ["Arroz", "15 %"]],
    sinIngredientes: ["Gluten"],
    analisis: { proteina: 28, grasa: 18, fibra: null, ceniza: null, kcal: null },
    formatos: null,
    verificar: true
  },
  {
    id: "nm-perro-adulto-mediano",
    linea: "nm", especie: "perro", edad: ["adulto"], tamano: ["mediano"],
    nombre: "Adulto razas medianas",
    completo: "Dibaq Natural Moments 5 Star Pavo y Pollo Adulto Razas Medianas",
    resumen: "39 % de pavo y pollo, arroz como único cereal.",
    descripcion: "La receta de todos los días para perros medianos: carnes de ave, arroz y hierbas mediterráneas como orégano, romero y tomillo.",
    proteinas: ["Pavo", "Pollo"],
    contiene: ["pavo", "pollo", "cereales"],
    necesidades: [],
    ingredientes: [["Pavo y pollo", "39 %"], ["Arroz", "único cereal"]],
    sinIngredientes: ["Trigo", "Maíz"],
    analisis: null,
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "nm-perro-ocean",
    linea: "nm", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Ocean salmón",
    completo: "Dibaq Natural Moments 5 Star Ocean",
    resumen: "Salmón como única proteína animal, con arroz.",
    descripcion: "36 % de salmón y arroz monograno, sin gluten. Omega 3 y 6 para la piel y el pelo, y protectores articulares. Lleva aceite de pavo.",
    proteinas: ["Salmón"],
    contiene: ["salmon", "pescado", "pavo", "cereales"],
    necesidades: ["pelaje", "alergias"],
    ingredientes: [["Salmón", "36 %"], ["Arroz", "19 %"], ["Aceite de pavo", ""]],
    sinIngredientes: ["Gluten"],
    analisis: { proteina: 26, grasa: 14, fibra: 3, ceniza: 7.9, kcal: 3539 },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "nm-perro-mountain",
    linea: "nm", especie: "perro", edad: ["adulto"], tamano: ["mini", "mediano", "grande"],
    nombre: "Mountain cordero",
    completo: "Dibaq Natural Moments 5 Star Mountain",
    resumen: "Cordero y pavo, hipoalergénico y fácil de digerir.",
    descripcion: "Un sabor de campo para perros adultos de todas las razas: cordero y pavo con arroz monograno.",
    proteinas: ["Cordero", "Pavo"],
    contiene: ["cordero", "pavo", "cereales"],
    necesidades: ["alergias", "digestion"],
    ingredientes: [["Cordero", ""], ["Pavo", ""], ["Arroz", "único cereal"]],
    sinIngredientes: ["Gluten"],
    analisis: { proteina: 27, grasa: 15, fibra: 2.9, ceniza: 8.9, kcal: 3554 },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "nm-perro-mobility",
    linea: "nm", especie: "perro", edad: ["adulto", "senior"], tamano: ["mini", "mediano", "grande"],
    nombre: "Mobility pavo y krill",
    completo: "Dibaq Natural Moments 5 Star Mobility",
    resumen: "El mayor aporte articular de la gama.",
    descripcion: "Pavo y krill con colágeno, condroitina, glucosamina, MSM y ácido hialurónico: 14,060 mg/kg de complejo articular para perros adultos y mayores que se mueven con dificultad.",
    proteinas: ["Pavo", "Krill"],
    contiene: ["pavo", "pescado", "cereales"],
    necesidades: ["articulaciones", "peso"],
    ingredientes: [["Pavo", "33 %"], ["Krill", ""], ["Arroz", "15 %"]],
    sinIngredientes: ["Gluten"],
    analisis: { proteina: 27, grasa: 10, fibra: 5, ceniza: 8.7, kcal: 3200 },
    formatos: ["2 kg", "12 kg"],
    verificar: true
  },
  {
    id: "nm-perro-ultralight",
    linea: "nm", especie: "perro", edad: ["adulto", "senior"], tamano: ["mini", "mediano", "grande"],
    nombre: "Ultralight",
    completo: "Dibaq Natural Moments 5 Star Ultralight",
    resumen: "25 % menos calorías para recuperar su peso.",
    descripcion: "Poca grasa y mucha fibra para que se sienta lleno, con L-carnitina y semillas de lino. Para perros adultos y mayores con sobrepeso.",
    proteinas: ["Pavo", "Pollo"],
    contiene: ["pavo", "pollo", "cereales"],
    necesidades: ["peso"],
    ingredientes: [["Pavo deshidratado", "17 %"], ["Pollo", "16 %"], ["Arroz", "13 %"]],
    sinIngredientes: ["Gluten"],
    analisis: { proteina: 25, grasa: 7, fibra: 7, ceniza: 6.7, kcal: 2765 },
    formatos: null,
    verificar: true
  },

  /* ================= NATURAL MOMENTS · GATOS (5 Star) ================= */
  {
    id: "nm-gato-kitten",
    linea: "nm", especie: "gato", edad: ["cachorro"], tamano: [],
    nombre: "Gatito pollo y pavo",
    completo: "Dibaq Natural Moments 5 Star Kitten",
    resumen: "Pollo y pavo para su primer año.",
    descripcion: "Proteína de ave y arroz para acompañar el crecimiento del gatito, con hierbas y antioxidantes naturales.",
    proteinas: ["Pollo", "Pavo"],
    contiene: ["pollo", "pavo", "cereales"],
    necesidades: [],
    ingredientes: [["Pollo", ""], ["Pavo", ""], ["Arroz", ""]],
    sinIngredientes: [],
    analisis: null,
    formatos: null,
    verificar: true
  },
  {
    id: "nm-gato-complete-care",
    linea: "nm", especie: "gato", edad: ["adulto", "senior"], tamano: [],
    nombre: "Complete Care",
    completo: "Dibaq Natural Moments 5 Star Complete Care",
    resumen: "Previene en una sola receta los cinco problemas más comunes del gato.",
    descripcion: "Bolas de pelo, sarro, articulaciones, defensas y saciedad, en un solo alimento para adultos y mayores. Pollo, pavo, huevo y aceite de salmón.",
    proteinas: ["Pollo", "Pavo"],
    contiene: ["pollo", "pavo", "pescado", "cereales"],
    necesidades: ["articulaciones", "peso"],
    ingredientes: [["Pollo", "24 %"], ["Pavo deshidratado", "21 %"], ["Arroz", "21 %"]],
    sinIngredientes: [],
    analisis: { proteina: 32, grasa: 12, fibra: null, ceniza: null, kcal: null },
    formatos: null,
    verificar: true
  },
  {
    id: "nm-gato-esterilizado",
    linea: "nm", especie: "gato", edad: ["adulto"], tamano: [],
    nombre: "Esterilizado pollo y pavo",
    completo: "Dibaq Natural Moments 5 Star Esterilizado Pollo y Pavo",
    resumen: "Hasta 95 % de proteína animal para gatos esterilizados.",
    descripcion: "Pollo y pavo con menos calorías para gatos esterilizados o que tienden a engordar.",
    proteinas: ["Pollo", "Pavo"],
    contiene: ["pollo", "pavo", "cereales"],
    necesidades: ["esterilizado", "peso"],
    ingredientes: [["Pollo", ""], ["Pavo", ""], ["Arroz", ""]],
    sinIngredientes: [],
    analisis: null,
    formatos: null,
    verificar: true
  },
  {
    id: "nm-gato-ocean-esterilizado",
    linea: "nm", especie: "gato", edad: ["adulto"], tamano: [],
    nombre: "Ocean esterilizado",
    completo: "Dibaq Natural Moments 5 Star Ocean Esterilizado",
    resumen: "Pollo y salmón con L-carnitina para controlar el peso.",
    descripcion: "47 % de pollo y salmón, arroz monograno y L-carnitina para gatos esterilizados.",
    proteinas: ["Pollo", "Salmón"],
    contiene: ["pollo", "salmon", "pescado", "cereales"],
    necesidades: ["esterilizado", "peso", "pelaje"],
    ingredientes: [["Pollo", "28 %"], ["Salmón deshidratado", "19 %"], ["Arroz", "19 %"]],
    sinIngredientes: [],
    analisis: { proteina: 32, grasa: 14, fibra: null, ceniza: null, kcal: null },
    formatos: null,
    verificar: true
  }
];
